services:
  redis:
    image: redis:6-alpine
    container_name: redis_service
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5


  authentication:
    container_name: authentication
    build: 
      context: ./authentication
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - app-network
    env_file:
      - ./authentication/.env
    environment:
      - REDIS_URI=redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy


  api-gateway:
    container_name: api-gateway
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    env_file:
      - ./api-gateway/.env
    depends_on:
      - authentication

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge