services:
  redis:
    image: redis:6-alpine
    container_name: redis_service
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  authentication:
    image: authentication-image:latest
    container_name: authentication-service
    build: 
      context: ./authentication
      dockerfile: Dockerfile
    ports:
      - "3007:3001"
    networks:
      - app-network
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://yadukrishnankzr:Wb4ueyOzdQW9kdio@crevio-cluster.on5qd.mongodb.net/authService
      - REDIS_HOST=redis_service
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - ./authentication:/app

  api-gateway:
    image: api-gateway-image:latest
    container_name: api-gateway
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - GATEWAY_PORT=3000
      - AUTH_SERVICE_URL=http://authentication-service:3001
    depends_on:
      - authentication
    volumes:
      - ./api-gateway:/app

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge