export const Messages = {
    SERVER_ERROR: "Internel server error",
    USER_EXIST: "User already exist",
    OTP_ERROR: "Error while sending OTP, Try again later",
    OTP_RESENT: "OTP has been resent successfully",
    INVALID_NAME: "Please enter a valid name (A - Z)",
    INVALID_EMAIL: "Please enter a valid email",
    INVALID_TOKEN: "Invalid Token",
    PASSWORD_LENGTH: "Your password must be at least 8 characters long",
    PASSWORD_LETTER: "Your password must contain at least one letter",
    PASSWORD_DIGIT: "Your password must contain at least one number",
    PASSWORD_SPECIALCHAR: "Your password must contain at least one special character",
    INCOMPLETE_FORM: "Please complete the form",
    OTP_EXPIRED: "Your OTP has been expired, try again",
    INCORRECT_OTP: 'The OTP you provided is incorrect',
    OTP_VERIFIED: 'OTP verification successful',
    TOKEN_EMPTY: 'No token Provided',
    USER_NOT_FOUND: "User not found, try to signup",
    ADMIN_NOT_FOUND: "Admin not found",
    INCORRECT_PASSWORD: "Incorrect password, try again",
    USER_BLOCKED: "Your are blocked from Crevio.",
    NO_ACCESS: "Unauthorized Access",
    LOGEDOUT_SUCCESS: "Logged out successfully",
    GOOGLE_ACC_FP : "Your account was created using Google. Please sign in with Google instead.",
    INVALID_FILE_FORMAT: "Invalid file format. Allowed: JPG, JPEG, PNG, WEBP.",
    DETAILS_NOT_FOUND_F: "Freelancer details not found.",
    DATA_NOT_FOUND: "Received data not found"
}